<option>Azucar</option>
<option>Arroz</option>
<option>Aceite</option>
<option>Aceptunas</option>
<option>Alcaparras</option>
<option>Harina</option>
<option>Pollo</option>
<option>Leche</option>
<option>Carne</option>
<option>Huevos</option>
<option>Pasta</option>
<option>Yogourt</option>
<option>Chicha</option>
<option>Jugo</option>
<option>Chocolate</option>
<option>Mortadela</option>
<option>Jamón</option>
<option>Queso</option>
<option>Mantequilla</option>
<option>Salsa de Tomate</option>
<option>Galletas</option>
